site_name: Request wet en regelgeving

theme:
  name: material
  langueage: en
  logo: logo.png
  favicon: logo.png
 
# Copyright
copyright: Copyright © 2024 Request Roleplay

site_url: https://requestapv.github.io

repo_name: GitHub
repo_url: https://github.com/FeddeNL/Request-APV

nav:
  - Home: index.md
  - Algemene Plaatselijke Verordening: apv.md
  - Keybinds: keybinds.md
  - Voertuigenlijst: voertuigenlijst.md
  - Wapens & Items: weapon-items.md